spring:
  profiles:
    include: oauth, dev
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
logging:
  level:
    dnd.studyplanner: debug
    org.hibernate.SQL: info
    org.hibernate.type: info
    com.amazonaws.util.EC2MetadataUtils: ERROR

server:
  tomcat:
    basedir: .
    accesslog:
        enabled: true
        directory: logs