spring:
  profiles:
    include: oauth, dev
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher  # Swagger와 MVC 충돌 방지

logging:
  level:
    dnd.studyplanner: debug
    org.hibernate.SQL: debug
    org.hibernate.type: trace