spring:
  profiles:
    include: oauth, dev
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    dnd.studyplanner: debug
    org.hibernate.SQL: debug
    org.hibernate.type: trace