spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(s35mqU/nqF072GnjW4RgoWivdpvF2ax4Tz+BcJ4wRi2Ay8PNvPs6stC9SJFR9+6XskBv3DwLcBspNp03oY3dxNqHRC9dhlO7ztyu8lBUF59IvIdU2cdzDmgmkG2hmO7E)
    username: ENC(bvODKY6arVl8NYstRGmyGHKduPrQFgQB)
    password: ENC(/3+pxmHYEpCS5cG1DaWhOGf8ojfr4SWY)

jasypt:
  encryptor:
    bean: jasyptStringEncryptor