name: DND Api CI/CD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  S3_BUCKET_NAME: dnd-deploy-bucket
  PROJECT_NAME: dnd-7th-9-backend

permissions:
  contents: read

jobs:
  build:
    # 실행 환경 지정
    runs-on: ubuntu-latest
    
    # Task 의 sequence 를 명시
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        
      # Build
      - name: Build with Gradle
        run: ./gradlew clean build -x test

      # 압축파일 형태로 전달
      - name: Make zip file
        run: zip -r ./$GITHUB_SHA.zip .

      # S3 Bucket 으로 copy
      - name: Deliver to AWS S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 cp \
          --region ap-northeast-2 \
          --acl private \
          ./$GITHUB_SHA.zip s3://$S3_BUCKET_NAME/$PROJECT_NAME/