# github repository Actions 페이지에 나타낼 이름
name: dnd-9th_CI/CD

# event trigger
on:
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    ## docker build & push
    - name: Docker build
      run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build --build-arg DEPENDENCY=build/dependency -t ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPO }} --platform linux/amd64 .
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPO }}
    ## deploy
  deploy:
    needs: build
    name: Deploy
    runs-on: [ self-hosted, dnd-9th ]
    steps:
      - name: Login to dkhub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Docker run
        run: |
          sudo systemctl start docker
          sudo docker rm -f $(docker ps -qa)
          sudo docker pull ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPO }}
          sudo docker run -d -p 9100:9100 ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPO }}
          docker image prune -f
